"""Fifty additional sample companies for seed_data and add_companies_extra.py.

Tuple order matches seed_data.Company: name, industry, website, contact_person,
contact_email, contact_phone, address, description.
"""

COMPANIES_EXTRA_50 = [
    ("Accenture India", "IT Services", "https://www.accenture.com/in-en", "Kavita Srinivasan", "kavita.srinivasan@accenture.com", "9000210001", "Accenture Campus, Bangalore", "Global professional services and IT consulting."),
    ("Capgemini India", "IT Services", "https://www.capgemini.com/in-en/", "Daniel Fernandes", "daniel.fernandes@capgemini.com", "9000210002", "Capgemini Knowledge Park, Mumbai", "Consulting, technology, and outsourcing."),
    ("Tech Mahindra", "IT Services", "https://www.techmahindra.com", "Pooja Kulkarni", "pooja.kulkarni@techmahindra.com", "9000210003", "Tech Mahindra SEZ, Pune", "Digital transformation and business services."),
    ("HCL Technologies", "IT Services", "https://www.hcltech.com", "Arvind Krishnan", "arvind.krishnan@hcl.com", "9000210004", "HCL Campus, Noida", "Global technology company."),
    ("Mphasis", "IT Services", "https://www.mphasis.com", "Lisa George", "lisa.george@mphasis.com", "9000210005", "Mphasis Tower, Bangalore", "Cloud and cognitive services."),
    ("Persistent Systems", "Software", "https://www.persistent.com", "Gaurav Joshi", "gaurav.joshi@persistent.com", "9000210006", "Persistent Campus, Pune", "Software product development services."),
    ("LTIMindtree", "IT Services", "https://www.ltimindtree.com", "Sandeep Pillai", "sandeep.pillai@ltimindtree.com", "9000210007", "LTIMindtree, Bangalore", "Technology consulting and digital solutions."),
    ("SAP Labs India", "Software", "https://www.sap.com/india", "Thomas Weber", "thomas.weber@sap.com", "9000210008", "SAP Labs, Bangalore", "Enterprise application software R&D."),
    ("Oracle India", "Technology", "https://www.oracle.com/in", "Jennifer Dsouza", "jennifer.dsouza@oracle.com", "9000210009", "Oracle Park, Hyderabad", "Database and cloud infrastructure."),
    ("Adobe India", "Software", "https://www.adobe.com/in", "Rohit Bansal", "rohit.bansal@adobe.com", "9000210010", "Adobe Tower, Noida", "Creative and digital experience software."),
    ("NVIDIA India", "Semiconductors", "https://www.nvidia.com/en-in", "Michael Chen", "michael.chen@nvidia.com", "9000210011", "NVIDIA Bangalore", "GPU computing and AI platforms."),
    ("Intel India", "Semiconductors", "https://www.intel.com/content/www/in/en/home.html", "Sarah Joseph", "sarah.joseph@intel.com", "9000210012", "Intel Campus, Bangalore", "Semiconductor design and manufacturing."),
    ("Qualcomm India", "Telecommunications", "https://www.qualcomm.com", "David Mathews", "david.mathews@qualcomm.com", "9000210013", "Qualcomm Hyderabad", "Wireless technology and mobile chipsets."),
    ("Texas Instruments India", "Semiconductors", "https://www.ti.com", "Anita Deshpande", "anita.deshpande@ti.com", "9000210014", "TI Campus, Bangalore", "Analog and embedded processing."),
    ("Salesforce India", "Cloud / SaaS", "https://www.salesforce.com/in", "Emily Roberts", "emily.roberts@salesforce.com", "9000210015", "Salesforce Tower, Hyderabad", "CRM and cloud software."),
    ("VMware India", "Cloud / Software", "https://www.vmware.com/in", "Kevin O'Brien", "kevin.obrien@vmware.com", "9000210016", "VMware Bangalore", "Virtualization and multi-cloud infrastructure."),
    ("Red Hat India", "Open Source / Software", "https://www.redhat.com/en/global/india", "James Wilson", "james.wilson@redhat.com", "9000210017", "Red Hat Pune", "Enterprise open-source solutions."),
    ("Paytm", "FinTech", "https://paytm.com", "Vijay Shekhar", "campus@paytm.com", "9000210018", "One97 Campus, Noida", "Digital payments and financial services."),
    ("PhonePe", "FinTech", "https://www.phonepe.com", "Rahul Chari", "talent@phonepe.com", "9000210019", "PhonePe HQ, Bangalore", "UPI and digital payments platform."),
    ("Razorpay", "FinTech", "https://razorpay.com", "Harshil Mathur", "careers@razorpay.com", "9000210020", "Razorpay, Bangalore", "Payment gateway and banking APIs."),
    ("Swiggy", "E-Commerce / Logistics", "https://www.swiggy.com", "Sriharsha Majety", "hr@swiggy.com", "9000210021", "Swiggy, Bangalore", "Food delivery and quick commerce."),
    ("Ola", "Mobility", "https://www.olacabs.com", "Bhavish Aggarwal", "careers@olacabs.com", "9000210022", "Ola Electric, Bangalore", "Ride-hailing and electric vehicles."),
    ("Uber India", "Mobility", "https://www.uber.com/in/en", "Pradeep Parameswaran", "india-careers@uber.com", "9000210023", "Uber Gurugram", "Ride-sharing and delivery."),
    ("Meesho", "E-Commerce", "https://www.meesho.com", "Vidit Aatrey", "talent@meesho.com", "9000210024", "Meesho, Bangalore", "Social commerce marketplace."),
    ("Freshworks", "SaaS", "https://www.freshworks.com", "Girish Mathrubootham", "careers@freshworks.com", "9000210025", "Freshworks Chennai", "Customer engagement software."),
    ("Chargebee", "SaaS", "https://www.chargebee.com", "Krish Subramanian", "jobs@chargebee.com", "9000210026", "Chargebee Chennai", "Subscription billing platform."),
    ("Zerodha", "FinTech", "https://zerodha.com", "Nithin Kamath", "careers@zerodha.com", "9000210027", "Zerodha Bangalore", "Stock broking and trading technology."),
    ("ICICI Bank", "Banking", "https://www.icicibank.com", "HR Campus", "campus@icicibank.com", "9000210028", "ICICI Towers, Mumbai", "Private sector banking and financial services."),
    ("HDFC Bank", "Banking", "https://www.hdfcbank.com", "Talent Acquisition", "campus@hdfcbank.com", "9000210029", "HDFC House, Mumbai", "Retail and corporate banking."),
    ("Axis Bank", "Banking", "https://www.axisbank.com", "Early Careers", "campus@axisbank.com", "9000210030", "Axis House, Mumbai", "Banking and financial services."),
    ("JPMorgan Chase India", "Banking / Finance", "https://www.jpmorganchase.com", "Mumbai HR", "campus-in@jpmchase.com", "9000210031", "JPMC Mumbai", "Global financial services."),
    ("Goldman Sachs India", "Investment Banking", "https://www.goldmansachs.com", "Bangalore HR", "campus-in@gs.com", "9000210032", "GS Bangalore", "Investment banking and securities."),
    ("Morgan Stanley India", "Finance", "https://www.morganstanley.com", "Mumbai Careers", "campus-in@morganstanley.com", "9000210033", "Morgan Stanley Mumbai", "Financial services and wealth management."),
    ("Siemens India", "Engineering / Manufacturing", "https://www.siemens.com/in", "Hans Mueller", "careers.in@siemens.com", "9000210034", "Siemens Kalwa, Mumbai", "Industrial automation and digitalization."),
    ("Honeywell India", "Engineering", "https://www.honeywell.com/in/en", "Robert Singh", "careers@honeywell.com", "9000210035", "Honeywell Bangalore", "Aerospace and building technologies."),
    ("Mercedes-Benz R&D India", "Automotive", "https://www.mercedes-benz.co.in", "Klaus Braun", "rnd-careers@mercedes-benz.com", "9000210036", "MBRDI Bangalore", "Automotive research and development."),
    ("Shell India", "Energy", "https://www.shell.in", "Emma Clarke", "careers-in@shell.com", "9000210037", "Shell Mumbai", "Oil, gas, and energy transition."),
    ("ReNew Power", "Renewable Energy", "https://www.renew.com", "Sumant Sinha", "careers@renew.com", "9000210038", "ReNew Gurugram", "Renewable energy generation."),
    ("Tata Power", "Energy", "https://www.tatapower.com", "Praveer Sinha", "careers@tatapower.com", "9000210039", "Tata Power Mumbai", "Integrated power utility."),
    ("Reliance Jio", "Telecommunications", "https://www.jio.com", "Akash Ambani", "careers@jio.com", "9000210040", "Jio HQ, Navi Mumbai", "Digital services and telecom."),
    ("Bharti Airtel", "Telecommunications", "https://www.airtel.in", "Gopal Vittal", "campus@airtel.com", "9000210041", "Airtel Centre, Gurugram", "Telecom and digital services."),
    ("Ericsson India", "Telecommunications", "https://www.ericsson.com/en/in", "Niklas Heuveldop", "careers.in@ericsson.com", "9000210042", "Ericsson Chennai", "5G and network infrastructure."),
    ("Nokia India", "Telecommunications", "https://www.nokia.com", "Pekka Lundmark", "careers.in@nokia.com", "9000210043", "Nokia Chennai", "Network equipment and software."),
    ("Samsung R&D Institute India", "Technology", "https://www.samsung.com/in", "KC Ryu", "srib-jobs@samsung.com", "9000210044", "SRI-B Bangalore", "Consumer electronics R&D."),
    ("Philips India", "Healthcare / Electronics", "https://www.philips.co.in", "Roy Jakobs", "careers.in@philips.com", "9000210045", "Philips India, Mumbai", "Health technology."),
    ("Dell Technologies India", "Technology", "https://www.dell.com/en-in", "Michael Dell", "in-careers@dell.com", "9000210046", "Dell Bangalore", "IT infrastructure and PCs."),
    ("IBM India", "IT Services", "https://www.ibm.com/in-en", "Arvind Krishna", "careers@ibm.com", "9000210047", "IBM India, Bangalore", "Hybrid cloud and AI."),
    ("LinkedIn India", "Technology", "https://www.linkedin.com", "Ryan Roslansky", "talent-in@linkedin.com", "9000210048", "LinkedIn Bangalore", "Professional networking platform."),
    ("Thoughtworks India", "IT Services", "https://www.thoughtworks.com/en-in", "Sudhir Tiwari", "careers@thoughtworks.com", "9000210049", "Thoughtworks Bangalore", "Technology consulting and agile delivery."),
    ("Atlassian India", "Software", "https://www.atlassian.com", "Mike Cannon-Brookes", "careers@atlassian.com", "9000210050", "Atlassian Bangalore", "Team collaboration software."),
]
